### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by shogowarrior** [metachris/micropython-ctl#10]
I am not very knowledgable about JS/TS so there's a very likely chance I did something wrong here.

I see the following error trying to connect to an invalid address:
`FetchError: request to http://localhost:32820/api/ failed, reason: connect ECONNREFUSED 127.0.0.1:3282`
 upon spamming `.connectNetwork()`. Was wondering if there's a way to handle this with a defined Exception?
to catch const resp = await fetch(`http://localhost:${WEBSERVER_PORT}/api/`)

**Comment by metachris** [comment]
Thanks for the report, will look into it shortly 👍

**Comment by metachris** [comment]
Can you check if this PR ☝️  fixes the issue?

You can install it with `npm install -g micropython-ctl@beta`. Afterwards `mctl version` should print `v1.13.8-beta2`.

**Comment by shogowarrior** [comment]
Let me give this a try! You are right, I am not able to figure out how to effectively do try catch in JavaScript ☹️; been mostly coding in Java/scala.

My use case it to convert input image and display it to to an OLED i2c connected to esp32. I have been using node-red for the flows and wrote a function node to do this for me: 

I am super interested in adding node-red nodes for the apis you have created to add drag and drop UI nodes for it.


I performed spam calls to check resiliency but would crash node-red with:

**Comment by metachris** [comment]
I think it would be really great to have those node-red nodes, and I'm happy to support you however I can.

A remarks on your code:

If `connectNetwork` succeeds without an exception, then you are guaranteed that the device is connected. Therefore the next 2 lines (check on `isConnected` shouldn't be necessary.

How do you import the module, actually? Is the execution environment web-based or Node.js-based? I don't have experience with node-red :)

**Comment by metachris** [comment]
One more remark -- it is possible to reuse one long-lasting connection, if you don't want to connect and disconnect every time. You can do this by calling `device.startInternalWebserver()`, although that name should probably change to `device.allowConnectionReuse()`

**Comment by shogowarrior** [comment]
> I think it would be really great to have those node-red nodes, and I'm happy to support you however I can.
> 

Give node red a try. It is nodejs based with webui to do flow programming . I have been fooling around it with it for 4 months for ifttt and iot but the possibilities are endless 😊. 

Having said that, just need to find time between jobs and 2 kids 😂.


> 
> A remarks on your code:
> 
> 
> 
> If `connectNetwork` succeeds without an exception, then you are guaranteed that the device is connected. Therefore the next 2 lines (check on `isConnected` shouldn't be necessary.
> 

You are right! They were debug code that can be removed.

> How do you import the module, actually? Is the execution environment web-based or Node.js-based? I don't have experience with node-red :)

This is a bit tricky in node red. A settings.js needs to be updated so that it can be used in a UI function  node or alternatively use user defined nodes to import packages.

**Comment by shogowarrior** [comment]
> One more remark -- it is possible to reuse one long-lasting connection, if you don't want to connect and disconnect every time. You can do this by calling `device.startInternalWebserver()`, although that name should probably change to `device.allowConnectionReuse()`

That is a great idea and thank you for the tip! I was been thinking about using a config node in node red. Will look up some plug-in code to reverse engineer 🤩
