### ISSUE TITLE
Node-RED support

### ISSUE THREAD

**Issue by shogowarrior** [metachris/micropython-ctl#9]
Thank you for adding this super-useful tool! I have been waiting for this 😁 . 

Adding Node-red nodes to call MicroPythonDevice methods will be a great addition to node-red. I am more than happy to contribute to the cause!

**Comment by metachris** [comment]
Oh sure, that sounds like a great idea! Am happy to support your effort. 

What are the steps needed?

**Comment by shogowarrior** [comment]
I am not sure either! let me get back to you on this soon!
